# Generated by Django 3.1 on 2020-11-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Dia del evento')),
                ('start_time', models.TimeField(verbose_name='Hora de Inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de Finalizacion')),
                ('state', models.BooleanField(default=True, verbose_name='Pendiente')),
                ('tipo_actividad', models.CharField(max_length=30, verbose_name='tipo actividad')),
                ('notes', models.TextField(blank=True, max_length=100, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agenda',
            },
        ),
    ]
