# Generated by Django 3.1 on 2020-11-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Actividad')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de finalizacion')),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripcion')),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='fotografias')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.lugar')),
                ('participantes', models.ManyToManyField(to='administrar.Persona')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'actividad',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la actividad')),
                ('descripcion', models.TextField(max_length=1000, null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo actividad',
                'verbose_name_plural': 'Tipo actividades',
                'db_table': 'tipo_actividad',
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.CharField(blank=True, max_length=30, null=True, verbose_name='trabajo')),
                ('Descripcion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripcion')),
                ('imagenes', models.ImageField(blank=True, max_length=500, null=True, upload_to='fotografias')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.actividad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.miembro')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'db_table': 'responsable',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.tipo_actividad'),
        ),
    ]
