# Generated by Django 3.1 on 2020-11-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Categoria')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], default='Ingreso', max_length=8, verbose_name='Tipo de movimiento')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descripcion')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('saldo', models.FloatField(default=0.0, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuesto',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], default='Ingreso', max_length=8, verbose_name='Tipo de movimiento')),
                ('cantidad', models.FloatField(default=0.0)),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripcion')),
                ('evidencia', models.ImageField(blank=True, max_length=500, null=True, upload_to='fotografias')),
                ('fondos', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='presupuesto.presupuesto')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.categoria')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimiento',
            },
        ),
    ]
