# Generated by Django 3.1 on 2020-11-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Puesto')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Iglesia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Iglesia',
                'verbose_name_plural': 'Iglesias',
                'db_table': 'iglesia',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('origen', models.CharField(choices=[('I', 'Internacional'), ('L', 'Local')], default='L', max_length=1, verbose_name='origen')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lugar',
                'verbose_name_plural': 'Lugares',
                'db_table': 'lugar',
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Persona')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'TipoPersona',
                'verbose_name_plural': 'TipoPersonas',
                'db_table': 'tipopersona',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('comun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comun.comun')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.lugar')),
                ('nombre_Iglesia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.iglesia')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.tipopersona')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'db_table': 'persona',
            },
            bases=('comun.comun',),
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('comun_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comun.comun')),
                ('sueldo', models.FloatField(default=0)),
                ('email', models.EmailField(blank='True', max_length=254, null=True, verbose_name='correo')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.cargo')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.lugar')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'db_table': 'miembro',
            },
            bases=('comun.comun',),
        ),
        migrations.AddField(
            model_name='iglesia',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.lugar'),
        ),
    ]
