# Generated by Django 3.1 on 2020-11-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos_sociales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadPorRango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha De Inicio')),
                ('fecha_limite', models.DateField(verbose_name='Fecha De Limite')),
            ],
            options={
                'verbose_name': 'Actividad Por Rango de Fecha',
                'verbose_name_plural': 'Actividades Por Rango de Fecha',
                'db_table': 'actividad_por_rango',
            },
        ),
        migrations.CreateModel(
            name='InformePastores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Informe_pastores',
                'verbose_name_plural': 'Informe Pastores',
                'db_table': 'informe_pastor',
            },
        ),
        migrations.CreateModel(
            name='Informes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Informes_generales',
                'verbose_name_plural': 'Informes de Eventos',
                'db_table': 'informe_general',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoPorRango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha De Inicio')),
                ('fecha_limite', models.DateField(verbose_name='Fecha De Limite')),
                ('gasto', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Presupuesto Por Rango de Fecha',
                'verbose_name_plural': 'Presupuesto Por Rango de Fecha',
                'db_table': 'presupuesto_por_rango',
            },
        ),
        migrations.CreateModel(
            name='ProyectoPorRango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha De Inicio')),
                ('fecha_limite', models.DateField(verbose_name='Fecha De Limite')),
            ],
            options={
                'verbose_name': 'Proyecto Por Rango de Fecha',
                'verbose_name_plural': 'Proyectos Por Rango de Fecha',
                'db_table': 'proyecto_por_rango',
            },
        ),
        migrations.CreateModel(
            name='InformeTipoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha De Inicio')),
                ('fecha_limite', models.DateField(verbose_name='Fecha De Limite')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_sociales.tipo_proyecto')),
            ],
            options={
                'verbose_name': 'Informe Por Tipo',
                'verbose_name_plural': 'Informes Tipo',
                'db_table': 'informe_por_tipo',
            },
        ),
    ]
