# Generated by Django 3.1 on 2020-11-07 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(max_length=1000, null=True, verbose_name='Descripcion')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo Proyecto',
                'verbose_name_plural': 'Tipo Proyectos',
                'db_table': 'tipo_proyecto',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donaciones', models.IntegerField(blank=True, verbose_name='Donaciones')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de Actividad')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripcion')),
                ('imagenes', models.ImageField(blank=True, max_length=500, null=True, upload_to='fotografias')),
                ('lugar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.lugar')),
                ('participantes', models.ManyToManyField(to='administrar.Persona')),
                ('tipo_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_sociales.tipo_proyecto')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajo', models.CharField(blank=True, max_length=30, null=True, verbose_name='trabajo')),
                ('Descripcion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descripcion')),
                ('imagenes', models.ImageField(blank=True, max_length=500, null=True, upload_to='fotografias')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_sociales.proyecto')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrar.miembro')),
            ],
        ),
    ]
